### PR TITLE
Add missing fields from the index

### PR DESCRIPTION
**Pull request by alexindigo**
When in development environment there is no npm-downloads service running, so fields are missing from the index and search page just crashes. That makes dev's day very long, sad and not very fruitful. 
This PR will help to reduce frustration for the community as a whole. :)

### CODE REVIEW

**Comment by tmpvar** [comment]
I'm not sure what you mean! is the npm-downloads thing you are talking about referring to https://github.com/aheckmann/npm-downloads?

I'm leaning towards not including transient values like `stars` and such at this level.  Willing to be convinced though..

**Comment by alexindigo** [comment]
Hey, I meant this guy [npm/download-counts](https://github.com/npm/download-counts). Let me explain with more details.

For example, I'm a Frontend developer and I've heard on podcast invitation to come and help to make community website better for mobile browsers. I've got all pumped up. I went to the website, I've found link to the github repo. I forked and cloned it. Then I read Readme file. :) It it said that I had to run not only node, but bunch of other services I never dealt with, like couchdb, redis and elastic. But neverfear there is soon-to-be-discontinued vagrant image for you, so I installed vagrant and download image, hope and will be turnkey solution to run the website so I can play with templates and views and make it look awesome on iPhone 4. :) After few hours of downloading bunch of stuff, I finally was able to run `npm run dev-db` inside the vagrant and `npm run dev` outside the vagrant. And was able to open first page. Type in some random package name (hoping it will be within the chunk I downloaded from the web) – just to see search page showing Error, instead expected no results or some results. Trying module pages and they work fine, but no search. Couple days later, that frontend developer spent learning couch and elastic and how to make them work together (instead of improving his favorite website), he realized that some fields are missing from the index, he tries different versions of the code (from master branch and from release tags) – no luck. There is no docs on the matter so he googles and finds couch2elastic plugin, that seems to work, but not exactly. Then poking around through the code and repos of the github organization that owns his favorite website, he manually adds missing fields to the index and everything falls into place.

So this PR is to reduce number of steps in the described process, and pre-populate missing fields (that used in the search query and making elastic to throw up when they not present) so people who want to work on something other then elastic-couch-aws integration can contribute to the project with less hassle. :)

And `stars` maybe not the most important field of them all, but it used in the query and the way it used it makes query to barf if it's not in the index: https://github.com/npm/newww/blob/master/facets/registry/show-search.js#L75

Thank you.

**Comment by tmpvar** [comment]
oh!  You should probably use https://github.com/npm/npm2es for this as it includes the download counts!

**Comment by alexindigo** [comment]
Haha, that is one hidden fork :) And one silly me. Thank you for the clarification.

**Comment by tmpvar** [comment]
no worries! good luck :smile:

**Pull request closed without merging**
